apiVersion: apps/v1
kind: Deployment
metadata:
  name: soma-api
  namespace: soma-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soma-api
  template:
    metadata:
      labels:
        app: soma-api
    spec:
      containers:
      - name: api
        image: soma-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: soma-config
              key: ENVIRONMENT
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: soma-config
              key: DEBUG
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: soma-config
              key: LOG_LEVEL
        command: ["python", "-m", "src.api.app"]
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        emptyDir: {}
