# Model configuration for different environments

default: &default
  demand_forecasting:
    model_type: "random_forest"
    hyperparameters:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 5
      random_state: 42
    features:
      time_series: ["quantity_lag_1", "quantity_lag_7", "quantity_ma_7"]
      categorical: ["genre", "price_category", "length_category"]
      numerical: ["book_age_months", "velocity_score"]
    validation:
      method: "time_series_split"
      n_splits: 5

  recommendation:
    content_based:
      similarity_metric: "cosine"
      min_similarity: 0.1
      max_recommendations: 50
    collaborative:
      method: "svd"
      n_components: 50
      random_state: 42
    hybrid:
      content_weight: 0.6
      collaborative_weight: 0.4

  rag:
    retrieval:
      method: "bm25_semantic"
      bm25_weight: 0.6
      semantic_weight: 0.4
      top_k: 5
    generation:
      model: "gpt-3.5-turbo"
      max_tokens: 500
      temperature: 0.7

development:
  <<: *default
  demand_forecasting:
    hyperparameters:
      n_estimators: 50  # Faster training for dev

production:
  <<: *default
  demand_forecasting:
    hyperparameters:
      n_estimators: 200  # Better performance for prod
      max_depth: 15

testing:
  <<: *default
  demand_forecasting:
    hyperparameters:
      n_estimators: 10  # Very fast for tests