version: 2

models:
  - name: stg_publishers
    description: "Cleaned publisher data"
    columns:
      - name: publisher_id
        description: "Unique publisher identifier"
        data_tests:
          - unique
          - not_null
      
  - name: stg_books
    description: "Cleaned book catalog data"
    columns:
      - name: book_id
        description: "Unique book identifier"
        data_tests:
          - unique
          - not_null
      - name: price
        description: "Book price"
        data_tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000

  - name: stg_sales
    description: "Cleaned sales transaction data"
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        data_tests:
          - unique
          - not_null
      - name: total_amount
        description: "Total transaction amount"
        data_tests:
          - dbt_utils.accepted_range:
              min_value: 0

  - name: stg_inventory
    description: "Cleaned inventory data"
    columns:
      - name: inventory_id
        description: "Unique inventory record identifier"
        data_tests:
          - unique
          - not_null