name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Install dbt dependencies
      run: |
        ls -la
        cd dbt
        dbt deps
        dbt run
        cd ..
      env:
        DBT_TARGET: ci
    
    - name: Generate test data for CI
      run: |
        python generate_synthetic_data.py
      env:
        DBT_TARGET: ci
        DBT_DUCKDB_PATH: ":memory:"
    
    - name: Run tests
      run: |
        chmod +x scripts/run-tests.sh
        ./scripts/run-tests.sh
      env:
        DBT_TARGET: ci
        DBT_DUCKDB_PATH: ":memory:"